import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      items: [{type: 'autogenerated', dirName: 'infrastructure'}],
    },
  ],
  guideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
};

export default sidebars;
